### ISSUE TITLE
Combat script stuck at "use skill"

### ISSUE THREAD

**Issue by fullblue** [steve1316/granblue-automation-pyautogui#102]
It seems like combat script always stuck at "use skill" when there is no targeting. Bot just don't click the "OK" button.

**Comment by steve1316** [comment]
When exactly does the "OK" button appear? I'm clicking a non-target skill and it immediately is casted and I see no popup that shows up.

**Comment by fullblue** [comment]
Like this
![Capture](https://user-images.githubusercontent.com/65227601/149854453-8dd9b550-4d79-43c2-9f0e-38f198bafc20.JPG)

**Comment by steve1316** [comment]
Oh, that one. Can you enable this and try again:

![chrome_TkmngoVSCK](https://user-images.githubusercontent.com/18709555/149854625-f3751875-02dd-4d6d-834d-604ae9dbecaf.png)

**Comment by fullblue** [comment]
lmao, never noticed that

**Comment by fullblue** [comment]
it works good with that
