### ISSUE TITLE
Feature Suggestions:

### ISSUE THREAD

**Issue by xerance** [steve1316/granblue-automation-pyautogui#106]
"Toggle refresh on/off to skip animations" - An option to toggle auto refresh on/off  when the attack button disappear

"Quick summon on CD support" - Make it so the GA scans the "quick summon ready" when in full auto and refresh cash and resume full auto. Would be a cool feature to spice up FA and utilize the quick summon to it's full effect without to much effort. Could also be integrated with a check before re-enabling FA.

![image](https://user-images.githubusercontent.com/16266200/150236741-b778ec21-dee1-4476-95d8-32216e33db3b.png)
![image](https://user-images.githubusercontent.com/16266200/150238318-056bb5d7-50a8-4bb3-8bbb-e6c05daecad2.png)

"Pick any summon failsafe when you can't find any summon that you picked for the quest/raid" - Option for a failsafe so the bot get stuck not finding a summon you want after x second to prevent having to restart the bot if you run out of Kaguya summons as an example while sliming.

"Generic mode for coop quests" - Similar to your current generic farming mode for quest but for coop rooms. just make the GA go to the coop room and start next one when the current one ends.

**Comment by steve1316** [comment]
v1.3.0 is out implementing your suggestions!
