### ISSUE TITLE
Adjustable delay for "status checks" to compensate for bad ping

### ISSUE THREAD

**Issue by xerance** [steve1316/granblue-automation-pyautogui#108]
example: https://puu.sh/IDMBq/20a4337a0b.mp4

due to page not loading faste enough with my ping, the attack button isn't visible before the GAA checks for it therefore breaking the intended function. This also sometimes happens with "check if summon page is visible" and so on.
Raids like gw 100-150 is completely unplayable due to slow load up and the small starting animation the raid has before attack is visible.

Suggested solution: adjustable/addition delay option for every "startup check" in settings to compensate for ping issues.

**Comment by steve1316** [comment]
v1.3.0 is out with the new Adjustments page implementing your feedback.
