### ISSUE TITLE
Sandbox loot screen detection

### ISSUE THREAD

**Issue by zorkings** [steve1316/granblue-automation-pyautogui#112]
I've noticed if I kill the sandbox node with an orange button on turn 1 it will be stuck there waiting for a loot screen as it does not click on the next arrow. Currently remedied by enabling refresh after attack so not a huge deal

Would there be possibility of adding the new sandbox zones as well?

**Comment by zorkings** [comment]
> What do you mean by orange button? Did you mean the orange "Attack" button? So you finished the battle on Turn 1 using only skills and not clicking the Attack button right?
> 
> Also yes, support for the 4 new Zones will be coming soon.

It was a few skills then attack button, yes. After the boss died it just hangs on the same screen with the NEXT button in bottom right spamming that it is looking for loot window (this only occurs with refresh off as refresh puts it at loot window)

**Comment by steve1316** [comment]
> It was a few skills then attack button, yes. After the boss died it just hangs on the same screen with the NEXT button in bottom right spamming that it is looking for loot window (this only occurs with refresh off as refresh puts it at loot window)

Alright thank you. I will check it out when I get the chance.

**Comment by steve1316** [comment]
> It was a few skills then attack button, yes. After the boss died it just hangs on the same screen with the NEXT button in bottom right spamming that it is looking for loot window (this only occurs with refresh off as refresh puts it at loot window)

Hmm, tested it out on my end and I cannot seem to replicate your issue unfortunately.

**Comment by zorkings** [comment]
> > It was a few skills then attack button, yes. After the boss died it just hangs on the same screen with the NEXT button in bottom right spamming that it is looking for loot window (this only occurs with refresh off as refresh puts it at loot window)
> 
> Hmm, tested it out on my end and I cannot seem to replicate your issue unfortunately.

Yeah no idea, I'll just leave the refresh on to work around it for now
