### ISSUE TITLE
Not Ready when arcarum without summon selected

### ISSUE THREAD

**Issue by Chu2P** [steve1316/granblue-automation-pyautogui#118]
if you're farming in arcarum sandbox, but don't have a support summon previously selected, app status is not ready. need to select different farming mode to select a summon before going back to sandbox

**Comment by steve1316** [comment]
Fixed by @KoiKomei in [be4c7a7](https://github.com/steve1316/granblue-automation-pyautogui/commit/be4c7a783828164d4f221afdf19a2d6a4b5cae19).
