### ISSUE TITLE
Cannot run the program

### ISSUE THREAD

**Issue by gn01102368** [steve1316/granblue-automation-pyautogui#129]
Hello
I cannot run the program. It always show "system error", "Cannot start the program. Because your file is missing api-ms-win-core-winrt-l1-1-0.dll"
I already re-install required program several times. Please tell me how should i do.

OS: windows7 sp1

**Comment by steve1316** [comment]
You need to find that .dll file online for your Windows. There are YouTube videos on how to find it.
