### ISSUE TITLE
Error farming rays of convergence

### ISSUE THREAD

**Issue by colpocleisis** [steve1316/granblue-automation-pyautogui#132]
There seems to be some issue in the bots logic to farming rays of convergence.
Both trying to navigate to the island, and if you were already on the island, selecting the quest, leads to the bot erroring out.

**Comment by steve1316** [comment]
Sorry it took so long to take a look at this. Tested with the mission `House of Happiness` at New Utopia and `A Girl Named Mika Episode 2` at The Edgelands both off and on their respective islands. Did not encounter this issue.
