### ISSUE TITLE
Event raid IM doesn't work

### ISSUE THREAD

**Issue by nothingworksendit** [steve1316/granblue-automation-pyautogui#133]
Whenever I try to farm the IM raid, it scrolls down and picks the solo battles, failing because it expects to reach the summon selection screen afterwards. VH and EX don't have that problem.

**Comment by nothingworksendit** [comment]
When I changed the resolution of my VM, I fixed the problem. Is there a limit or something?

**Comment by steve1316** [comment]
The bot is rated for 1080p and 1440p as those are the resolutions that I test on so that may explain why changing your resolution on your VM works depending on what your new resolution is.
