### ISSUE TITLE
GW EX+ error (log)

### ISSUE THREAD

**Issue by rei69** [steve1316/granblue-automation-pyautogui#135]
0:00:03 [STATUS] Starting bot process on a new thread now...

0:00:02 [DISCORD] Unable to start Discord process. Either you opted not to turn it on or your included token/user id inside the Settings or settings.json are invalid.

0:00:03 [INFO] Recalibrating the dimensions of the window...
0:00:03 [INFO] Using static window configuration...
0:00:03 [SUCCESS] Dimensions of the window has been successfully recalibrated.

0:00:03 **********************************************************************
0:00:03 **********************************************************************
0:00:03 [INFO] Screen Size: Size(width=1920, height=1080)
0:00:03 [INFO] Game Window Dimensions: Region(64, 0, 564, 1080)
0:00:03 **********************************************************************
0:00:03 **********************************************************************

0:00:03 ######################################################################
0:00:03 ######################################################################
0:00:03 [FARM] Starting Farming Mode for Guild Wars.
0:00:03 [FARM] Farming 3x Repeated Runs at Extreme+.
0:00:03 [FARM] Combat Script name: reload.txt
0:00:03 [FARM] Combat Script: ['Turn 1:', 'repeatManualAttackAndReload', 'end']
0:00:03 [FARM] Summons: ['Huanglong']
0:00:03 [FARM] Group #: 5
0:00:03 [FARM] Party #: 1
0:00:03 ######################################################################
0:00:03 ######################################################################

0:00:04 [INFO] Bot is at the Home screen.
0:00:06 [WARNING] Failed to find the CLOSE button.

0:00:06 [GUILD.WARS] Now navigating to Guild Wars...
0:00:10 Sorting second
0:00:10 [INFO] Occurrence for EVENT_BANNER found at: [(154, 713)]
0:00:19 Sorting second
0:00:19 [INFO] Occurrence for EVENT_RAID_BATTLE found at: [(145, 545), (145, 653)]

0:00:19 [GUILD.WARS] Now proceeding to farm meat.
0:00:24 [GUILD.WARS] Now hosting Extreme+ now...
0:00:25 Sorting first
0:00:25 [INFO] Occurrence for AP_30 found at: [(206, 715), (410, 715)]

0:00:25 [ERROR] Bot encountered exception in Farming Mode: 
Traceback (most recent call last):
  File "C:\Users\Unnamed\Desktop\Granblue.Automation.v1.7.0\backend\bot\game.py", line 955, in start_farming_mode
    GuildWars.start(first_run)
  File "C:\Users\Unnamed\Desktop\Granblue.Automation.v1.7.0\backend\bot\game_modes\guild_wars.py", line 207, in start
    GuildWars._navigate()
  File "C:\Users\Unnamed\Desktop\Granblue.Automation.v1.7.0\backend\bot\game_modes\guild_wars.py", line 91, in _navigate
    MouseUtils.move_and_click_point(ap_locations[2][0], ap_locations[2][1], "ap_30")
IndexError: list index out of range

0:00:34 ######################################################################
0:00:34 ######################################################################
0:00:34 [FARM] Ending Farming Mode due to encountering Exception.
0:00:34 ######################################################################
0:00:34 ######################################################################

0:00:38 [STATUS] Stopping the bot and terminating its Thread.
0:00:38 [STATUS] Closing Python process...

Saved message log to: log 2022-06-21 20-42-47.txt
Child process finished with code 0

**Comment by steve1316** [comment]
Tracking issue at #142.
