### ISSUE TITLE
Failed to find the PROVING_GROUNDS_MISSIONS button.

### ISSUE THREAD

**Issue by Anuise** [steve1316/granblue-automation-pyautogui#136]
This is my log.
[log 2022-07-9 04-04-22.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/9074584/log.2022-07-9.04-04-22.txt)
My proving grounds pages:
https://media.discordapp.net/attachments/884577329953771590/994632832683085884/unknown.png?width=480&height=676
warning window:
https://media.discordapp.net/attachments/884577329953771590/994592618908504126/unknown.png

**Comment by steve1316** [comment]
Very late by now, but many changes have been made since the issue was first reported. Closing this issue as the issue is no longer reproducible.
