### ISSUE TITLE
Proving Grounds- Failed to find Attack Button

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#137]
When doing proving grounds, the bot doesn't wait long enough for the fight to load, causing it to think that the fight has already ended. This then causes the bot to hang once the fight actually loads.

Here's the log:
[log 2022-08-20 08-20-41.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/9387073/log.2022-08-20.08-20-41.txt)

**Comment by steve1316** [comment]
![Granblue_Automation_AOg2S17OVi](https://user-images.githubusercontent.com/18709555/185751690-7aaace9c-1320-42fb-a765-bfa4d8268252.png)

Can you try adjusting this setting to a higher number and try again?

**Comment by PortablePanda** [comment]
Yep, that did it! Thank you for the quick response.
