### ISSUE TITLE
Combat script for dimensional halo equals 0

### ISSUE THREAD

**Issue by KoiKomei** [steve1316/granblue-automation-pyautogui#14]
There are 2 lines starting from line 1582 of game.py in which, for some reason, the dimensional script gets set to 0.
This causes the bot to crash cause it expects a string but it receives an integer. Obviously this also makes it so that you never load the correct combat script.

**Comment by steve1316** [comment]
Oh! That was leftover code when I was fixing a bug with the bot not being able to read custom combat scripts in the config.ini. Fixing it right away.

**Comment by steve1316** [comment]
Alright, let me know how it goes!

**Comment by KoiKomei** [comment]
It should be good. Another issue closed 👍
