### ISSUE TITLE
Failed to Guild Wars mode

### ISSUE THREAD

**Issue by enustah28** [steve1316/granblue-automation-pyautogui#140]
Guild Wars mode is not working.
Specifically, if you try to select EX+, it will malfunction with the following error statement.
This could not be resolved by re-downloading or partially deleting the Python file.
Thank you for your support.

[ERROR] Bot encountered exception in Farming Mode: 
Traceback (most recent call last):
  File "E:\***\backend\bot\game.py", line 955, in start_farming_mode
    GuildWars.start(first_run)
  File "E:\***\backend\bot\game_modes\guild_wars.py", line 207, in start
    GuildWars._navigate()
  File "E:\***\backend\bot\game_modes\guild_wars.py", line 91, in _navigate
    MouseUtils.move_and_click_point(ap_locations[2][0], ap_locations[2][1], "ap_30")
IndexError: list index out of range

**Comment by captain-dui** [comment]
Open "guild_wars. Py"

Change line 91 to "mouseutils. Move_and_click_point (ap_locations [1] [0], ap_locations [1] [1]," ap_30 "),

I don't know why, but it seems to work,

You need to back up the original file first

**Comment by enustah28** [comment]
If I modify only line 91, I seem to get an error in the definition.

Do you think the same action (→ mouseutils ) is necessary for all MouseUtils?
Perhaps that is a rudimentary question, sorry, but thank you in advance.

0:00:25 [ERROR] Bot encountered exception in Farming Mode: 
Traceback (most recent call last):
  File "E:\@@@@Granblue.Automation.v1.8.0\backend\bot\game.py", line 939, in start_farming_mode
    GuildWars.start(first_run)
  File "E:\@@@@Granblue.Automation.v1.8.0\backend\bot\game_modes\guild_wars.py", line 205, in start
    GuildWars._navigate()
  File "E:\@@@@Granblue.Automation.v1.8.0\backend\bot\game_modes\guild_wars.py", line 89, in _navigate
    mouseutils. move_and_click_point (ap_locations [1] [0], ap_locations [1] [1]," ap_30 ")
NameError: name 'mouseutils' is not defined


0:00:28 ######################################################################
0:00:28 ######################################################################
0:00:28 [FARM] Ending Farming Mode due to encountering Exception.
0:00:28 ######################################################################
0:00:28 ######################################################################

**Comment by captain-dui** [comment]
My mistake ,my Translation software Convert uppercase letters to lowercase letters,
the correct answer is"MouseUtils.move_and_click_point(ap_locations[1][0], ap_locations[1][1], "ap_30")"

**Comment by enustah28** [comment]
Oops sorry, it was simpler than that.
I was able to check the operation successfully and solved the problem.
Thank you for your quick response. ;-)
