### ISSUE TITLE
The higher difficulty raids...

### ISSUE THREAD

**Issue by enustah28** [steve1316/granblue-automation-pyautogui#141]
Let me tell you about another point that has been bothering me since yesterday.

The Python data seems to have a selection for the higher difficulty raids such as Belial and Beelzebub, but when I actually check the tool, those items do not seem to exist.

Is this a bug or is it intentional?
Thank you in advance.

**Comment by steve1316** [comment]
Yeah it is intentional. I can look into adding support for them if someone really wants to farm them.

**Comment by enustah28** [comment]
I have been wanting to farm the raid by building a fully automatic organization for this multi.

In reality, this raid is not recommended due to its high difficulty, but if you can handle it individually, please describe it separately here and I will handle it.

I will leave it up to you to decide if this feature should be a standard feature.
Thank you in advance.

**Comment by steve1316** [comment]
Added support for the remaining leftover high difficulty raids:

    Lvl 250 Beelzebub
    Lvl 250 Belial
    Lvl 300 Super Ultimate Bahamut
    Lvl 275 Mugen

Changes available in v1.9.0.
