### ISSUE TITLE
Antique Cloth fail found Ch 70 Erste Kingdom

### ISSUE THREAD

**Issue by stevenaprilianto** [steve1316/granblue-automation-pyautogui#143]
![image](https://user-images.githubusercontent.com/50316830/189179532-97a05932-0f8c-4cd9-bc00-10b361cbec43.png)

bot scroll to bottom, and cant find the mission

0:00:01 [QUEST] Beginning process to navigate to the mission: Erste Kingdom Episode 4...
0:00:02 [WARNING] Failed to confirm the bot's location at HOME.

0:00:02 [INFO] Moving back to the Home screen...
0:00:04 [WARNING] Failed to find the CLOSE button.
0:00:05 [QUEST] Bot is currently on the correct island.
0:00:10 [WARNING] Failed to confirm the bot's location at YOU_RETREATED_FROM_THE_RAID_BATTLE.

0:00:10 [QUEST] Moving to Chapter 70 node...
0:00:12 [QUEST] Now bringing up the Summon Selection screen for "Erste Kingdom Episode 4"...
0:00:13 [WARNING] Failed to find the MISSION_ERSTE_KINGDOM_EPISODE_4 button.
0:00:14 [WARNING] Failed to find the EPISODE_4 button.
0:00:15 [WARNING] Failed to find the OK button.
0:00:18 [WARNING] Failed to confirm the bot's location at NOT_ENOUGH_AP.

0:00:18 [INFO] AP auto-restore check passed. Continuing to Party Selection...
0:00:23 [WARNING] Failed to confirm the bot's location at SELECT_A_SUMMON.

**Comment by steve1316** [comment]
Ah I see. The scroll is too strong for 1080p screens.

**Comment by steve1316** [comment]
Fix available in v1.9.0.

**Comment by stevenaprilianto** [comment]
sorry for late reply, anyway thanks a lot
