### ISSUE TITLE
Requires EXTRA organization option.

### ISSUE THREAD

**Issue by enustah28** [steve1316/granblue-automation-pyautogui#145]
I have confirmed cases where Mugen HL and Diaspora HL are unable to farm the raid due to the following error repeatedly due to the use of EXTRA organization.

0:02:24 [WARNING] Failed to find the PARTY_SET_A button.
0:02:26 [WARNING] Failed to find the PARTY_SET_B button.
0:02:28 [WARNING] Failed to find the PARTY_SET_A button.
0:02:30 [WARNING] Failed to find the PARTY_SET_B button....

Ps.
Also, we are now able to do high difficulty multis, but we were unable to confirm this regarding lvl 250 for Lucilius.
I will report it as well.

**Comment by steve1316** [comment]
Do you happen to have a picture of what this EXTRA image looks like? I do not have those raids unlocked so I cannot work on this further.

**Comment by enustah28** [comment]
No, the [party_set_extra.jpg] should work, but for some reason I could not reference it.
And it appears to be trying to reference set A and set B.

**Comment by steve1316** [comment]
Oh, I see. The `part_set_extra.jpg` is only used for Arcarum Sandbox. Are you not able to use the standard parties from Set A or B? If not, can you attach a video showcasing the normal way you start either of those raids? I would need to visualize how someone would start those types of raids as I do not have access to those newer types of raids.

**Comment by enustah28** [comment]
Oh, sorry.
I didn't know it was in that condition.
I can provide you with a simple video like this if you like.

https://drive.google.com/file/d/1OdR--_EGxU6kHY6-wWwGD-dIXv7uGYkM/view?usp=sharing

**Comment by steve1316** [comment]
Thanks for the video, it was super helpful. Fix is in v1.9.2 so let me know how it goes!

**Comment by enustah28** [comment]
I am very happy to hear that it was useful to you.
I hope that Automation will continue to be loved and used for a long time and that it will continue to develop further.
Thank you for the quick update!

**Comment by steve1316** [comment]
Thanks for the feedback!
