### ISSUE TITLE
[feature request] Support for non 1080p/1440p resolution

### ISSUE THREAD

**Issue by Ekytfy** [steve1316/granblue-automation-pyautogui#147]
1. Log 1 bot failed to enter arcarum sandbox quest zone 1
[log 2022-09-21 23-19-28.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/9622836/log.2022-09-21.23-19-28.txt)

2. Log 2 bot failed to navigate to arcarum sandbox zone 2
[log 2022-09-21 23-22-16.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/9622839/log.2022-09-21.23-22-16.txt)

**Comment by steve1316** [comment]
Just realized that your resolution is 768p. Can you try again at 1080p or 1440p? The bot has only been tested against those resolutions so anything other than those is completely up in the air on whether or not the bot will function as expected.

**Comment by Ekytfy** [comment]
I run this on a laptop with a 1366x768 screen so I can't test it with another resolution, well only sandbox has this problem so I'm just gonna bear with it

**Comment by Ekytfy** [comment]
If you don't intend to support for other resolution you can close this steve

**Comment by steve1316** [comment]
v2.4.0 allows non 1080p/1440p resolutions now.
