### ISSUE TITLE
#Questions Run on Win 7

### ISSUE THREAD

**Issue by stevenaprilianto** [steve1316/granblue-automation-pyautogui#149]
Can i run this on Win 7 with 3gb ram and 1366x768 resolution?

![image](https://user-images.githubusercontent.com/50316830/193605159-e0db6cae-b554-4235-8402-551a8f90cff0.png)

![image](https://user-images.githubusercontent.com/50316830/193605393-3d6219be-3d1c-40ae-893f-8fd9d86c4415.png)

**Comment by stevenaprilianto** [comment]
I try install all requirement right now, but point number 7 make me not sure hahaha

![image](https://user-images.githubusercontent.com/50316830/193606799-8fbc45a5-c2d9-4743-a5cd-0f8378faa1ad.png)

**Comment by steve1316** [comment]
Yeah, it might be a bit difficult. One of the blocking factors was the recent switch to a Typescript frontend along with WebView2 so I do not believe it is available for Windows 7.

I believe some people have been using this on 720p but I do not know how this works on 768p, but in the end the bot has been tested against 1080p and 1440p.

**Comment by Ekytfy** [comment]
I also use 1366x768 resolution and the only feature I can't use is only arcarum. Just make sure to run chrome in full screen and auto-hide the taskbar

**Comment by steve1316** [comment]
One cumbersome way to bypass the Windows 10 requirement is to manually create your own settings.json and then manually starting the bot via terminal/console with `python main.py` in the /backend/ folder.

**Comment by stevenaprilianto** [comment]
got trouble on this :')

![image](https://user-images.githubusercontent.com/50316830/193636920-5f6991ad-7254-4e1a-aa35-d5424ab4be49.png)

**Comment by Ekytfy** [comment]
You need MSVC 2015-2019  [Link](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) also make sure to install all the requirements needed to run it

**Comment by stevenaprilianto** [comment]
> You need MSVC 2015-2019 [Link](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) also make sure to install all the requirements needed to run it

already install all of them, the list on Requirements

seems i need reinstall to win 7 sp 1

**Comment by stevenaprilianto** [comment]
i give up, still same error vc 2015 problem hahaha

**Comment by steve1316** [comment]
FYI, a user posted a solution on the Discord on how to run the bot on Windows 7 and to resolve those .dll errors. I have pinned the comment so you can check it there. 👍
