### ISSUE TITLE
Pending Battle Logic

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#15]
Hello there Steve!

New find would be the pending battle logic.

![image](https://user-images.githubusercontent.com/17860803/110623559-4ad12080-819d-11eb-989e-ff275e3b38dd.png)

When on the quest result screen the bot clicks the pending battles button but it doesn't clear the popups.

![image](https://user-images.githubusercontent.com/17860803/110623631-66d4c200-819d-11eb-97ba-b6e519f35d4d.png)

This skyscope one is pretty new.

There is also the friend request one. 

![image](https://user-images.githubusercontent.com/17860803/110623676-76540b00-819d-11eb-8187-73cf96b47503.png)

If it can't find the pending battle tab it just exists to the home page.

I'm linking the logs

[Pending battle.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6115494/Pending.battle.txt)

**Comment by steve1316** [comment]
Thank you for letting me know! I will get on this as soon as I can.

**Comment by steve1316** [comment]
Just updated the bot to handle Skyscope mission popups. Let me know how it goes!
