### ISSUE TITLE
Raid Loot Error

### ISSUE THREAD

**Issue by zorkings** [steve1316/granblue-automation-pyautogui#156]
I always seem to get this error whenever it is checking pending battle loot
[log 2022-12-15 15-45-18.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/10240551/log.2022-12-15.15-45-18.txt)

**Comment by steve1316** [comment]
Hmm that's weird. Can you try `pip install packaging` in a terminal and see if the problem pops up again.

**Comment by zorkings** [comment]
fixed
