### ISSUE TITLE
Coop loop 

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#17]
Hello there Steve!

This time I found out that the script doesn't wanna start the coop room after the first loop.

![image](https://user-images.githubusercontent.com/17860803/110981201-1d37d300-8367-11eb-954d-5352f0def0cd.png)

It already selected the party.

I'm linking the log too.

[coop_loop.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6132112/coop_loop.txt)

**Comment by steve1316** [comment]
Alright, thanks for letting me know! I will get a fix out as soon as I can.

**Comment by steve1316** [comment]
Just pushed an update that fixes this issue. Let me know how it goes!
