### ISSUE TITLE
Can the bot use raid code of other websites to farm raids?

### ISSUE THREAD

**Issue by zk1479** [steve1316/granblue-automation-pyautogui#174]
The Twitter Developer account is expensive to get now. Can we use the raid codes provided by other websites like https://gbs.eriri.net/? The timeliness seems also good.

**Comment by steve1316** [comment]
It could do that with a headless client. Although the fact that the website uses user-submitted API keys to cycle through its requests does have me wondering about its longevity. The raid rework by cygames is coming out in a few days so I will be taking a look at that.
