### ISSUE TITLE
Error Code 9009

### ISSUE THREAD

**Issue by Delfinoneto** [steve1316/granblue-automation-pyautogui#175]
What is this error? 

"Child process error: stream did not contain valid UTF-8

Saved message log to: log 2023-04-6 11-04-34.txt
Child process finished with code 9009"

How can i fix it?

**Comment by steve1316** [comment]
Hmm, was that the only message recorded in the log? Nothing else?

**Comment by steve1316** [comment]
Closing this issue as I have not encountered this issue from my testing and without repro steps, not much can be done with this.
