### ISSUE TITLE
Support for Nobiyo summon

### ISSUE THREAD

**Issue by stijnvcp** [steve1316/granblue-automation-pyautogui#18]
Hi,

Nobiyo is another good misc summon to use when farming repeatable quests since he also gives 15% to item drop rate and exp.

Could you consider adding support for this?

https://gbf.wiki/Nobiyo

**Comment by steve1316** [comment]
Sure thing! I will add support for Nobiyo support summon when I have the time today.

**Comment by steve1316** [comment]
Just updated the bot by adding support for Nobiyo support summon. Let me know how it goes!

**Comment by stijnvcp** [comment]
Working like a charm, thanks for the quick update.
