### ISSUE TITLE
generic V2 static window calibration sidebar

### ISSUE THREAD

**Issue by AthTop** [steve1316/granblue-automation-pyautogui#186]
It seems v2 mode takes into account the sidebar from mobage if using the static window calibration setting, which leads to it failing if using DMM.
Disabling static window calibration seems to not work either as sub window is never found.

line129 in window.py 
            Window.sub_left = 0
changing this to sub_start as it should probably have been makes sub window be detected but cords are all messed up.

**Comment by steve1316** [comment]
Should be fixed in v3.0.4.
