### ISSUE TITLE
Module Missing

### ISSUE THREAD

**Issue by SolaceOfSins** [steve1316/granblue-automation-pyautogui#192]
![image](https://user-images.githubusercontent.com/131605942/233849979-83b8a921-7e09-4e1b-8d39-0512975dc7e2.png)
This is popping up when I press start, not sure if I am missing something or it's related to something else.

**Comment by steve1316** [comment]
When you did the installation command in your terminal, did any error messages pop up? In addition, does anything show up when you do `pip show pyautogui`?

**Comment by SolaceOfSins** [comment]
I just ran the install command again and it is downloading something which didn't happen last time. Though it still says the same thing in the bot. 

Ran the command you sent me and got this. 
![image](https://user-images.githubusercontent.com/131605942/233878464-e3aa7a36-8cca-4a9c-b89a-eada75211d59.png)

**Comment by steve1316** [comment]
> Ran the command you sent me and got this.

I believe you mispelled `pyautogui` for `pyautogu`. Anyways, maybe manually installing pyautogui with `pip install pyautogui==0.9.53` helps.

**Comment by steve1316** [comment]
Not sure why the install command did not install everything. `pip install discord.py==2.0.1` should resolve that.

**Comment by SolaceOfSins** [comment]
![image](https://user-images.githubusercontent.com/131605942/234264477-f9fd924d-8804-4739-b01a-bb78782edcc7.png)
 Just noticed the updates so I'm gonna see if running that will come with everything..

**Comment by SolaceOfSins** [comment]
![image](https://user-images.githubusercontent.com/131605942/234269271-132e751d-3df3-4cc3-917b-0b8a153a1802.png)

**Comment by SolaceOfSins** [comment]
It works now, thanks for the assistance!
