### ISSUE TITLE
[bug] Investigate reports of the recent mouse changes breaking mouse clicks

### ISSUE THREAD

**Issue by steve1316** [steve1316/granblue-automation-pyautogui#196]
## Description
> in the newer versions, the mouse clicks arent getting registered properly, any idea why?

> When you click twice at random, the bot stops by pressing the button at the bottom.

https://github.com/steve1316/granblue-automation-pyautogui/blob/a5312469e7e0f46167bad21f87edf909e8df58f2/src-tauri/backend/utils/mouse_utils.py#LL72C1-L110C21

**Comment by jstwayy** [comment]
I've noticed that this happens outside of "bezier curve mouse movement" option. As long as this option is enabled for me, I don't have any issues with registering clicks.
