### ISSUE TITLE
Virtualiztaion

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#2]
Hello there Steve!

Keep up the good work!

Your applications works very well on my Windows 10 machine.

My problem is I tried to circumvent the separate machine part of the application.

It is a windows 10 machine running in VMware workstation and while it starts up and finds the home button it doesn't move the mouse.

I just wanted to know if I messed up or if the application can't run in a virtual environment. 

qwe8585.

**Comment by steve1316** [comment]
Hello there!

This is one aspect of this program that I wish I knew how to overcome, the restriction of taking over the cursor. I am not sure why I did not think about Virtualization xD. Personally, I have no other experience with Virtualization aside from using BlueStacks to play Android games on PC.

It seems that the program's OCR capability in your virtual machine seems to be running fine but if we can figure out what is causing it to not move the mouse, I can update the description of this application to say that it can support virtualization!

Can you tell me what the terminal outputs when it finds the Home button of the GBF window and it does not move the mouse? I would say upload the saved log from the program, but I have not been diligent enough to flesh out the logging feature to extend to the entirety of the application yet to tell the user any and all errors.

**Comment by qwe8585** [comment]
[test.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/5813042/test.txt)

Here it is. I'm still not sure if it's on me.

**Comment by steve1316** [comment]
I was able to replicate this error on my own VMware Workstation. Just pushed out an update fixing this issue. Let me know if the bot is able to run for you now!

I have tested it at resolutions 1280x960 and 1920x1080 on my Workstation virtual machine.

**Comment by qwe8585** [comment]
Thanks Steve it's working now! 

You solved that so fast!
