### ISSUE TITLE
Invalid utf8 sequence?

### ISSUE THREAD

**Issue by pakulu** [steve1316/granblue-automation-pyautogui#201]
I was setting everything up, finally getting it to work and the next time i started my computer, this error pops up before even starting 

[log 2023-07-25 23-26-08.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/12165826/log.2023-07-25.23-26-08.txt)

**Comment by steve1316** [comment]
Seeing that you mentioned that it was working the first time before your computer was shutdown, I imagine something must have changed on your end.

Error originates from EasyOCR so not much I can do from here.

**Comment by pakulu** [comment]
Hmm I see. Guess I'll try reinstalling the requirements see what happens. Thanks for the quick reply

**Comment by pakulu** [comment]
Hey there, its me again. The error mightve been fixed after that but new issues are arising. The log shows it.
Bot encountered exception in Farming Mode NoneType object has no attribute 'shape'
AttributeError: 'NoneType' object has no attribute 'shape'

[log 2023-07-27 18-24-55.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/12185760/log.2023-07-27.18-24-55.txt)

**Comment by steve1316** [comment]
New logs show that it's the exact same error as before.

**Comment by pakulu** [comment]
That is true, didnt realize. After messing around for a while i got a bunch of different errors, some referenced in the wiki so it was an easy fix. Looks like im just back to square 1 now :thinking:

**Comment by steve1316** [comment]
Sorry for the late response. Error in the last posted log file shows that it failed to find the Arcarum banner image on the home page. The other messages saying invalid utf-8 sequence seems to not be the true culprit here. For now, I will close this issue.
