### ISSUE TITLE
Can't install EasyOCR / Torch

### ISSUE THREAD

**Issue by ChikyuTenshi** [steve1316/granblue-automation-pyautogui#210]
I'm unable to install any of the following

- torch===1.12.0+cu116
- torchvision===0.13.0+cu116
- torchaudio===0.12.0+cu116
- easyocr~=1.6.2

![Error](https://github.com/steve1316/granblue-automation-pyautogui/assets/20892295/d0c637da-3e9e-4b85-b074-20d8911ce22d)

**Comment by steve1316** [comment]
Just double-checking but when you do `python --version`, it says `3.8.3` right? And when you installed Python, you selected `Install to PATH`?

**Comment by ChikyuTenshi** [comment]
Alright so the error seems to be from my end, after removing other versions on Python, PyTorch is installing as it should, I'll close this ticket once I make sure everything is working as intended

I apologise for the inconvenience
