### ISSUE TITLE
Selecting to farm Primach anima doesn't let you select correct Raid to join.

### ISSUE THREAD

**Issue by stijnvcp** [steve1316/granblue-automation-pyautogui#22]
![image](https://user-images.githubusercontent.com/75256118/113486840-893ec000-9469-11eb-88e0-55a6da2cde91.png)

**Comment by steve1316** [comment]
Just updated the bot and fixed the missing frontend support for Primarch Raids. Let me know how it goes!

**Comment by stijnvcp** [comment]
thanks for the quick update, works perfectly
