### ISSUE TITLE
Unite And Fight

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#25]
Hello there Steve!

It has finally arrived. Unite and fight event is here.
I know you actually mentioned it but I hope we can get support for it. 
Thanks in advance!

qwe8585.

**Comment by steve1316** [comment]
Don't worry! Support for Guild Wars is on the way very shortly!

**Comment by steve1316** [comment]
Just updated the bot to support Guild Wars. Let me know how it goes!

**Comment by qwe8585** [comment]
Thanks again Steve it's working well!

**Comment by steve1316** [comment]
Closing issue as Guild Wars has ended.
