### ISSUE TITLE
Summon loop.

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#26]
Hello there Steve!

My newest find is a summon loop bug.

![Summon_loop](https://user-images.githubusercontent.com/17860803/113990415-ba483780-9851-11eb-8137-8fb5ec9a096d.png)

The script scroll to the bottom but if doesn't find the selected summon it just loops around trying to find it.

I'm linking the log too:
[Summon_loop.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6277058/Summon_loop.txt)

qwe8585.

**Comment by steve1316** [comment]
Thank you for letting me know and including the log! I will get on this right away!

**Comment by steve1316** [comment]
Just updated the bot to fix the case where Event, Event (Token Drawboxes), and Guild Wars were unable to detect the bottom of the Summon Selection page. Let me know how it goes!
