### ISSUE TITLE
is there a way to reload after every attack? and cant find home button issue see image

### ISSUE THREAD

**Issue by readmynameplease** [steve1316/granblue-automation-pyautogui#28]

**Comment by readmynameplease** [comment]
https://imgur.com/a/F2HPlSX

**Comment by steve1316** [comment]
Can you upload  a screenshot of what your granblue fantasy main page looks like? Maybe the Menu button on the main page was obscured by something. Additionally, what resolution is your screen size? I have used the bot at 1080p and 1440p.

Also, reloading after every attack is coming in a rework of Combat Mode. It is currently in-progress.

**Comment by readmynameplease** [comment]
https://imgur.com/a/pnDaW44

**Comment by steve1316** [comment]
Ah I see the problem now. Can you select the following window size as shown below and try starting the bot again?

![Screenshot 2021-04-10 223808](https://user-images.githubusercontent.com/18709555/114293749-8d607400-9a4d-11eb-88f4-c12259db26df.png)

**Comment by readmynameplease** [comment]
[Log.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6291354/Log.txt)
tried it and it detected it but theres issue on the log

**Comment by steve1316** [comment]
By any chance, are you somehow hiding the Mobage side bar on the left by moving the window to be slightly outside your monitor? I have my game window positioned in the following way every single time I use the bot:

![Screenshot 2021-04-11 014555](https://user-images.githubusercontent.com/18709555/114297809-ad9d2c80-9a67-11eb-98a9-49da4e8062a7.png)

The only way I could replicate your Region of (-1, _, _, _) was moving my window slightly off-screen so that the Mobage side bar was no longer visible. The first number of your Region() should be about 50-70, depending on screen size.

**Comment by readmynameplease** [comment]
it's working now is it possible to support the 3rd screen size?

**Comment by steve1316** [comment]
Refreshing after every attack is coming in a currently work-in-progress Combat Mode overhaul which you can take a look at in the open pull request. Unfortunately, there are still a lot of bugs I need to work out with the new overhaul for me to release it to everyone.

Additionally, this current screen size will only be supported for the time being as it will take a lot of time to redo every single template image to make it work. I may change my mind about this later, we shall see.

**Comment by readmynameplease** [comment]
ok! and how do I speed up the Mouse movement? it's really slow

**Comment by steve1316** [comment]
Currently, there are two types of mouse movement: 
1. Non-Bezier Curve mouse movement for fast but bot-like. Setting `mouse_speed` in your config.ini less than 1 will make it go really fast.
2. Bezier Curve mouse movement for slow but human-like. If `mouse_speed` in your config.ini is less than 1, the library that I use for Bezier Curve mouse movement will default it to 1.
