### ISSUE TITLE
NM 150 support

### ISSUE THREAD

**Issue by readmynameplease** [steve1316/granblue-automation-pyautogui#30]
pls put a support for NM 150 for guild wars thanks!

**Comment by steve1316** [comment]
Just added support for NM150. Let me know how it goes!

**Comment by readmynameplease** [comment]
not working for me

**Comment by steve1316** [comment]
The Combat Mode rework-in-progress is in the branch named `combat_mode_optimization`.

Closing this issue as Guild Wars has ended.
