### ISSUE TITLE
CAPTCHA Sound Alert

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#31]
Requesting a looping sound alert for when CAPTCHA pops up, to make it easier to notice. Possibly with the option of choosing your own sound and loop duration.

Thank you so much for this wonderful project!

**Comment by steve1316** [comment]
Thank you for the suggestion! I will try to get this done when I have time, but this will most likely come after my overhaul for Combat Mode is done and released.

**Comment by steve1316** [comment]
Just updated the bot to play the CAPTCHA.mp3 in the root of the project folder when a CAPTCHA is detected.
