### ISSUE TITLE
Proving Grounds

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#33]
Hello there Steve!

Proving Grounds event is here.
I hope we can get support for it.
Thanks in advance!

qwe8585.

**Comment by steve1316** [comment]
Thank you for letting me know. I will add support when I get some free time!

**Comment by steve1316** [comment]
Just updated the bot to support Proving Grounds. Let me know how it goes!

**Comment by qwe8585** [comment]
Thanks for the help Steve!

My observations:
![image](https://user-images.githubusercontent.com/17860803/116070441-ec98c800-a68c-11eb-8307-445bcf2dde96.png)

For some reason the script likes to get stuck on the summon page.
I'm linking the logs too:
[proving grounds_logs.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6376407/proving.grounds_logs.txt)

**Comment by qwe8585** [comment]
It seems that proving grounds has a special summon screen.

**Comment by steve1316** [comment]
Just updated the bot fixing the Summon Selection loop for Proving Grounds. Let me know how it goes!

**Comment by steve1316** [comment]
Closing issue as Proving Grounds has ended.
