### ISSUE TITLE
QtQuick module issue

### ISSUE THREAD

**Issue by Yining1** [steve1316/granblue-automation-pyautogui#34]
Hi there Steve! 

Something tells me this likely is an issue with my machine, but have you come across this error before? 

$ python main.py
QQmlApplicationEngine failed to load component
/granblue-automation-pyautogui/gui/qml/main.qml:1:1: plugin cannot be loaded for module "QtQuick": Cannot load library \granblue-automation-pyautogui\venv\lib\site-packages\PySide2\qml\QtQuick.2\qtquick2plugin.dll: The specified module could
 not be found.

The odd part is that qtquick2plugin.dll is indeed in that folder...

**Comment by steve1316** [comment]
A user had the exact same error as you before in issue #1 

They had Python 3.8.6 installed so they uninstalled it, installed Python 3.8.3, selected add to PATH, and then installed the dependencies as outlined in the instructions. Can you follow that and get back to me on whether it worked for you?

**Comment by Yining1** [comment]
That solved my problem, thank you so much!
