### ISSUE TITLE
 Failed to find the HOME button.

### ISSUE THREAD

**Issue by Yining1** [steve1316/granblue-automation-pyautogui#35]
Hi Steve! 

I'm currently running into an issue with locating buttons on the browser. Here's my current setup:
![image](https://user-images.githubusercontent.com/16738632/116010938-e9db9b80-a5d6-11eb-9692-ff7adfe9050f.png)
I went through some of the other questions people have asked and made sure that the window is at the full height of my screen and nothing is obscuring it, but for some reason, the bot still cannot find any of the HOME buttons. 

I'm currently using Chromium (Version 92.0.4488.0 (Developer Build) (64-bit)), with 100% page zoom. 
For GBF browser settings, I have bottom menu on, side bar type on slide, auto resizing off, and window size small. 

I also gave it a quick shot on just regular Chrome (Version 90.0.4430.85 (Official Build) (64-bit)), and I'm finding the same issues. I've attached the logs below! Let me know if you need any further details!
[01.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6373218/01.txt)

**Comment by steve1316** [comment]
Ah, I think I know the issue, can you select the "medium" window size?

![Screenshot 2021-04-25 154445](https://user-images.githubusercontent.com/18709555/116012075-34f8ad00-a5dd-11eb-9e72-ecc413d85997.png)

If so, then I will need to clarify in my instructions that this window size is necessary.

**Comment by Yining1** [comment]
Oh, that works! clicking the medium window size fixed my problem, thanks so much!
