### ISSUE TITLE
Error Refreshing Summons

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#38]
Recently, it seems as if I get an error whenever the program tries to refresh summons. It gets to the Trial Battle selection screen, but stops at this screen; error log included.
![image](https://user-images.githubusercontent.com/82384904/116965678-5b24e980-ac7c-11eb-8a3e-e164d7d3228f.png)

```
0:00:00 [INFO] Initializing EasyOCR reader. This may take a few seconds...
0:00:04 [INFO] EasyOCR reader initialized.

0:00:07 [INFO] Moving back to the Home screen...

0:00:12 [INFO] Optimizing window dimensions...
0:00:12 [INFO] Optimizing window dimensions complete.

0:00:12 ********************************************************************************
0:00:12 ********************************************************************************
0:00:12 [INFO] Screen Size: Size(width=1920, height=1080)
0:00:12 [INFO] Game Window Dimensions: Region(64, 80, 474, 946)
0:00:12 ********************************************************************************
0:00:12 ********************************************************************************

0:00:12 ################################################################################
0:00:12 ################################################################################
0:00:12 [FARM] Starting Farming Mode for Event (Token Drawboxes).
0:00:12 [FARM] Farming 50x Repeated Runs at EX Event Raid.
0:00:12 ################################################################################
0:00:12 ################################################################################


0:00:12 [INFO] Initializing settings for Event...
0:00:12 [INFO] Settings initialized for Event...
0:00:12 [INFO] Bot is at the Home screen.
0:00:16 [INFO] Occurrence for EVENT_BANNER found at: Point(x=148, y=713)
0:00:21 [INFO] Now hosting Event Raid...

0:00:29 [INFO] Now waiting for event_raid_extreme to vanish from screen...
0:00:30 [SUCCESS] Image successfully vanished from screen...
0:00:33 [INFO] AP is available. Continuing...
0:00:33 [INFO] Now checking if bot is currently at Summon Selection screen...
0:00:33 [INFO] Bot is currently at Summon Selection screen.
0:00:33 [INFO] Now attempting to find: BAHAMUT
0:00:36 [WARNING] Failed to find the BOTTOM_OF_EVENT_SUMMON_SELECTION button.
0:00:39 [WARNING] Failed to find the BOTTOM_OF_EVENT_SUMMON_SELECTION button.
0:00:42 [WARNING] Failed to find the BOTTOM_OF_EVENT_SUMMON_SELECTION button.
0:00:44 [WARNING] Failed to find the BOTTOM_OF_EVENT_SUMMON_SELECTION button.
0:00:49 [WARNING] Could not find any of the specified Summons.

0:00:49 [INFO] Now refreshing Summons...

0:00:52 [INFO] Moving back to the Home screen...
0:01:08 [WARNING] Failed to find the PLAY_ROUND_BUTTON button.
0:01:11 [WARNING] Failed to find the CHOOSE_A_SUMMON button.

0:01:11 [ERROR] Bot encountered exception in Farming Mode: 
Traceback (most recent call last):
  File "D:\Desktop\GBF Bot\bot\game.py", line 1138, in start_farming_mode
    summon_check = self._select_summon(self._summon_list, self._summon_element_list)
  File "D:\Desktop\GBF Bot\bot\game.py", line 435, in _select_summon
    self._reset_summons()
  File "D:\Desktop\GBF Bot\bot\game.py", line 464, in _reset_summons
    self.mouse_tools.move_and_click_point(choose_a_summon_location[0], choose_a_summon_location[1] + 187, "choose_a_summon")
TypeError: 'NoneType' object is not subscriptable


0:01:11 ################################################################################
0:01:11 ################################################################################
0:01:11 [FARM] Ending Farming Mode.
0:01:11 ################################################################################
0:01:11 ################################################################################
```

**Comment by steve1316** [comment]
I just ran a couple of runs intentionally having the bot reset summons while copying your settings of farming EX Event Raids for Event (Token Drawboxes) and they all completed successfully. How often does this happen for you? Does this happen consecutively one after the other? 

This error occurs when the bot failed to click the "Old Lignoid".

![trial_battles_old_lignoid](https://user-images.githubusercontent.com/18709555/116967292-d085bf80-ac66-11eb-8c3b-b093d2f2e22d.png)

**Comment by PortablePanda** [comment]
It happens extremely frequently, I would say that I can only successfully refresh summons one in every five tries.

If it matters, I'm using Microsoft Edge with smooth scrolling disabled, and playing in high resolution mode.

**Comment by steve1316** [comment]
Okay, I have recreated the behavior on Edge with smooth scrolling off and playing in high res graphics. The problem here is that on Edge with and without smooth scrolling off, the page scrolls way more from 1 single scroll than any other browser, like Chrome. Can you retry on another Chromium-based browser, like Chrome or Canary? For reference, I use Canary.

**Comment by PortablePanda** [comment]
I moved to Canary with default flags and medium graphics, and so far I haven't been able to run the bot long enough to reach a summon refresh, as it gets stuck on searching for Event Nightmares. So far, I haven't been able to find any reason for it.
[Searching for Nightmare.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6425309/Searching.for.Nightmare.txt)

**Comment by steve1316** [comment]
What screen did the bot end up at when it was stuck checking for Event Nightmares?

**Comment by PortablePanda** [comment]
Alright, refreshing summons seems to be fine!

As for the Event Nightmare check, it ends up stuck on the loot screen, here.

![image](https://user-images.githubusercontent.com/82384904/117194867-9b868380-adb2-11eb-9177-75edec1b0f5c.png)

**Comment by steve1316** [comment]
Okay, just found out that there was an additional different popup for auto-recovered AP, which I only thought there were one.

Please redownload the bot again and let me know if this fixed both the Event Nightmare loop and getting stuck checking for AP!

**Comment by PortablePanda** [comment]
Finished testing! With auto-fill AP off, the bot still closes out the refill menu and hangs. With auto-fill AP on, the bot properly closes out the refilled prompt and continues.

**Comment by steve1316** [comment]
Just updated the bot to attempt to fix your issue. It is difficult to figure out what is going on because I cannot seem to replicate your issue, 1440p or 1080p, auto refill on or off. Let me know how this goes for you.

**Comment by PortablePanda** [comment]
I'm set to 1080p resolution, using Chrome Canary with all flags default except for Calculate Window Occlusion off. Just downloaded the new update, current results are:

AP Autofill On, Results Screen: Successful
AP Autofill On, Event Screen: Successful
AP Autofill Off, Results Screen: Successful
AP Autofill Off, Event Screen: Successful

Everything seems good for now! If I run into another error, I'll mention it. Thank you!

**Comment by steve1316** [comment]
Good to know it worked out for you!
