### ISSUE TITLE
Xeno Diablo Clash

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#39]
Hello there Steve!

I know we have support for the normal showdowns.
But Xeno Diablo Clash is here!
I hope we can get support for it.
Thanks in advance!

qwe8585.

**Comment by steve1316** [comment]
Just updated the bot to support Xeno Clashes from now on. Let me know how it goes!

**Comment by qwe8585** [comment]
Thanks a lot steve!

My observation for now is this one:
![Xeno diablo nightmare](https://user-images.githubusercontent.com/17860803/117565087-dab51d00-b0af-11eb-88db-31164113e948.PNG)
The bot finds the nightmare popup but loops around on between the popup and the difficulty selector popup.
I'm sending you the log too:
[Xeno diablo nightmare.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6447144/Xeno.diablo.nightmare.txt)

**Comment by qwe8585** [comment]
Also Steve there is some weirdness going with the script deciding that the battle concluded suddenly when it in fact did not.

**Comment by steve1316** [comment]
Neglected the fact that some people might not have fought the Nightmares 3 times before using the bot so from now on and if enabled, the Level 90 Nightmare will be fought until skipping is enabled.

Also, I have reverted a change from yesterday from another issue that caused the bot thinking the battle concluded suddenly all the time. Let me know how it goes!

**Comment by manafount** [comment]
Hey steve!

I'm getting this when attempting to start Xeno Clash now:
```
[STATUS] Starting bot on a new Thread...
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\manaf\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\manaf\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\manaf\granblue-automation-pyautogui\main.py", line 48, in run_bot
    self._game = Game(queue = queue, is_bot_running = is_bot_running, combat_script = combat_script, debug_mode = debug_mode)
  File "C:\Users\manaf\granblue-automation-pyautogui\bot\game.py", line 139, in __init__
    self._enable_xeno_clash_nightmare = config.getboolean("xeno_clash", "enable_xeno_clash_nightmare")
  File "C:\Users\manaf\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 828, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
  File "C:\Users\manaf\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "C:\Users\manaf\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "C:\Users\manaf\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Users\manaf\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'xeno_clash'
```

**Comment by steve1316** [comment]
Yeah, I have not figured out a clean way to generate a new config.ini if the template has been changed without overwriting the file every single time the bot is booted up. But considering the fact that the template is very rarely changed, like in the case of a new event type like Xeno Clash, I figured leaving it as is will be enough.

**Comment by PortablePanda** [comment]
Adding onto this! Would it be possible to get Xeno clashes added to the Raid section so we can join other fights?

**Comment by steve1316** [comment]
Just updated the bot to support farming Raids of all Xeno Clash Raids. Let me know how it goes!

**Comment by steve1316** [comment]
Closing this issue as Xeno Clash Diablo has ended.
