### ISSUE TITLE
Ping Issues

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#4]
Hello there Steve!

Keep up the good work!

It's me again. What I found this time is that because my ping is high the bot tries to do things that didn't happen yet.

It's still the same virtual windows 10 machine.

qwe8585.

**Comment by qwe8585** [comment]
![Ping](https://user-images.githubusercontent.com/17860803/105831356-e4b28480-5fc6-11eb-900e-87eb9b966600.png)

**Comment by steve1316** [comment]
Thank you for letting me know about this. Currently, the bot is optimized towards approximately ~120ms. I'm in the process of adding configurable options to the config.ini that will allow you to adjust the timings between actions.

**Comment by steve1316** [comment]
I just pushed an update that will allow you to adjust the idle time after performing a skill/summon. You do not need to worry about the idle time after clicking the Attack button as the bot will now properly wait until the current Turn is complete and the next Turn has started before continuing.

**Comment by qwe8585** [comment]
Thanks for the help Steve it's not easy playing with EU ping but i'm not giving up!

**Comment by qwe8585** [comment]
I don't know how feasible it is but could you add more idling checks? 

What I actually had a problem with was the summoning reset for example. 

It tried to click the OK button before the OK even loaded and it caused the script to stop.

**Comment by qwe8585** [comment]
After testing more it seems the current build of the script is more stable Steve.

**Comment by steve1316** [comment]
I have made numerous changes and included more location checks. It seems that the bot is now more stable when I tested using network throttled on "Fast 3G" via the Chrome Dev Tools. Please let me know how it works out for you!

**Comment by qwe8585** [comment]
The script just completed the highest number of consecutive runs to date Steve. Thanks for the help!

**Comment by steve1316** [comment]
Glad to hear it!
