### ISSUE TITLE
Raid Already Defeated

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#41]
Requesting for the bot to automatically close and proceed if the "This raid has already been defeated" window appears due to using a skill on a raid which has already reached 0 HP.

Also, sorry for the double issue opening! Is it better to open one issue at a time for separate cases, or post multiple issues/suggestions in one thread?

**Comment by steve1316** [comment]
Opening a new issue for a separate bug would be greatly helpful in keeping everything organized into their own threads.

I have put out an update which should *hopefully* fix this bug.

**Comment by steve1316** [comment]
Reverted the change due to it causing a new bug. This issue will be on pause until I get the specific "This raid has already been defeated" popup so I can grab its image asset so I can deal with this issue. 

If you or anyone else ever encounter this specific popup, I would greatly appreciate it if you take a screenshot of the popup itself and upload it to this thread.

**Comment by PortablePanda** [comment]
Alright! As far as I'm aware, there are at least two different versions of the pop-up, so I'll go for it once I have a bit of time.

**Comment by steve1316** [comment]
Yeah, I thought there was only one version of that popup during combat, which was the "This battle has ended. The foe was defeated." Did not realize there was another one haha.

**Comment by steve1316** [comment]
Oh, if the texts on those 2 versions are the same, then there is no need to do anything as Combat Mode already checks for this header frequently:

![battle_concluded_header](https://user-images.githubusercontent.com/18709555/117870555-1b986780-b251-11eb-9b2d-10018baf2055.png)

**Comment by PortablePanda** [comment]
Just posting that I haven't forgotten about this, it's just taken a while to get the pop-up.

**Comment by PortablePanda** [comment]
Yep, seems this is still happening!

```0:23:39 ################################################################################
0:23:39 ################################################################################
0:23:39 [COMBAT] Starting Combat Mode.
0:23:39 ################################################################################
0:23:39 ################################################################################


0:23:39 [COMBAT] Now loading up combat script at D:/Desktop/granblue-automation-pyautogui-main/scripts/full_auto Earth.txt
0:23:40 [COMBAT] Reading command: turn 1:
0:23:40 [COMBAT] Starting Turn 1.
0:23:41 [COMBAT] Reading command for this Turn block: character2.useskill(3)
0:23:44 [COMBAT] Character 2 uses Skill 3.
0:23:50 [COMBAT] Reading command for this Turn block: enablefullauto
0:23:50 [COMBAT] Bot will now attempt to enable Full Auto...

0:23:53 [COMBAT] Bot has reached end of script. Automatically attacking until battle ends or Party wipes...```

**Comment by steve1316** [comment]
I was finally able to confirm that this problem has been resolved from the latest commit for this issue. Bot will now properly detect that the battle ended prematurely. Closing this now.
