### ISSUE TITLE
Impossible Grand Order

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#43]
Hello there Steve!

Impossible Grand Order raid isn't supported yet if I saw it right.
I hope we can get support for it.
Thanks in advance!

qwe8585.

**Comment by steve1316** [comment]
Just updated the bot to include support for Lvl 200 Grand Order plus:
- Lvl 200 Akasha
- Lvl 150 Lucilius

Let me know how it goes!

**Comment by manafount** [comment]
Thanks a bunch for adding these, I'll be testing out Akasha today!

Any chance you could also add Primarchs?

**Comment by steve1316** [comment]
I already added support for the Primarchs except for the "Four Primarchs" Raid because I did not know what people would farm that Raid for.

**Comment by manafount** [comment]
People farm the Four Primarchs for halos that are needed to 6* uncap the Eternals.

**Comment by steve1316** [comment]
Alright, I will get to work on that after the maintenance is over.

**Comment by steve1316** [comment]
Just updated the bot to support Four Primarchs Raid farming the 4 Halos. Let me know how it goes!

**Comment by qwe8585** [comment]
Thanks for all the support Steve!

**Comment by steve1316** [comment]
Closing issue due to the original issue had been resolved.
