### ISSUE TITLE
Failing to Select Summon

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#44]
Sometimes, the game doesn't recognize the click when choosing a summon, which causes it to terminate. I'm wondering if this is an anti-botting measure for the first summon slot.

```0:37:21 [INFO] Resting period complete.

0:37:25 [EVENT] No Event Nightmare detected. Moving on...
0:37:31 [INFO] AP is available. Continuing...
0:37:31 [INFO] Now attempting to find: SHIVA
0:37:34 [SUCCESS] Found SHIVA Summon at Point(x=146, y=473).

0:37:39 [CAPTCHA] CAPTCHA not detected. Moving on to Party Selection...
0:37:40 [WARNING] Failed to find the PARTY_SET_A button.
0:37:40 [WARNING] Failed to find the PARTY_SET_B button.
0:37:41 [WARNING] Failed to find the PARTY_SET_A button.
0:37:41 [WARNING] Failed to find the PARTY_SET_B button.
0:37:42 [WARNING] Failed to find the PARTY_SET_A button.

0:37:42 [ERROR] Bot encountered exception in Farming Mode: 
Traceback (most recent call last):
  File "D:\Desktop\granblue-automation-pyautogui-main\bot\game.py", line 1263, in start_farming_mode
    start_check = self._find_party_and_start_mission(self._group_number, self._party_number)
  File "D:\Desktop\granblue-automation-pyautogui-main\bot\game.py", line 520, in _find_party_and_start_mission
    raise Exception("Could not find Set A.")
Exception: Could not find Set A.


0:37:42 ################################################################################
0:37:42 ################################################################################
0:37:42 [FARM] Ending Farming Mode.
0:37:42 ################################################################################
0:37:42 ################################################################################```

**Comment by steve1316** [comment]
I encounter the same issue playing normally as well. Sometimes a UI element just does not respond at all, like selecting a Support Summon. Tried various methods to try to circumvent it, but it always comes back.

**Comment by PortablePanda** [comment]
Is it possible to add in checks to see if the element was properly clicked before the bot advances to the next step, and if not, to repeat?

**Comment by steve1316** [comment]
It is possible, but due to how uncommon the issue happens, I rather not implement it as it would add more downtime to the bot as it would constantly check if the UI element was properly clicked. At that point, restarting the bot would be much better.

**Comment by PortablePanda** [comment]
Would it be possible to add an option to automatically restart the bot when something causes it to hang or self-terminate? As well as a hotkey to pause it without window focus, maybe.

**Comment by steve1316** [comment]
My thinking of having the bot fail catastrophically is so the bot does not do anything unnecessary if it fails or hangs and for the user to keep an eye on it every now and then.

In addition, due to the way the bot is structured from the outset, being able to pause is not feasible at the moment.

**Comment by steve1316** [comment]
Closing issue as the original issue had already been addressed as something that I cannot resolve at the moment.
