### ISSUE TITLE
Ultimate Bahamut + Lindwurm Raids

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#46]
Hello! Requesting that UBaha gets added to the raid finder, as a source of lots of Primarch Anima/Trial Fragments/Centrums/Meteorites/Summon Anima.

**Comment by PortablePanda** [comment]
Also, I just realized, Lindwurm isn't on the list either!

**Comment by steve1316** [comment]
Sorry about the delay, got busy with my other projects. Will get to this when I get a chance.

**Comment by steve1316** [comment]
Just added support for Ultimate Bahamut (N and HL) and Lindwurm raids. Let me know how it goes!
