### ISSUE TITLE
Dread Barrage Missions 

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#47]
Hello there Steve!

The script crashes when the dread barrage missions popup comes up:
![image](https://user-images.githubusercontent.com/17860803/122908711-bad27380-d354-11eb-960c-ccdfece54e91.png)

I'm linking the log:
[Dread Barrage.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6693376/Dread.Barrage.txt)

Also Dread Barrage is now a token drawbox type event I don't know if that changes anything.

Thanks in advance!
qwe8585

**Comment by steve1316** [comment]
Alright, fixed that bug by completely removing support for Unparalleled Foes. For only 2 runs a day, it is not worth it to support it anymore so as to reduce bugs like this. Let me know how it goes!

**Comment by qwe8585** [comment]
Thanks Steve it works!
