### ISSUE TITLE
Skill Kill Hangs

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#48]
The bot can't seem to handle when waves/battles end due to skill use, such as when slime blasting. As of now, you need to put extra commands after the skill which will wipe the wave to make sure the bot won't progress to the next turn while death animations are playing, then put the skills to be used on the next turn, which causes the bot to waste a turn attacking. Trying to put all of the skills on the same turn causes the bot to skip past them when the "next* button appears, wasting the action.

**Comment by steve1316** [comment]
Closing issue as the new command `back` has been implemented to facilitate slime farming.
