### ISSUE TITLE
Combat system 2.0 

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#49]
Hello there Steve!

The bot doesn't recognize the full auto button if it's in a combat system 2.0 battle:

![image](https://user-images.githubusercontent.com/17860803/125336517-2a34f500-e34e-11eb-8d09-2604821ba401.png)

![image](https://user-images.githubusercontent.com/17860803/125336556-391ba780-e34e-11eb-8b89-84e2f4d7215b.png)

I'm linking the log:
[COMBAT 2.0.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6803552/COMBAT.2.0.txt)

Thanks in advance!
qwe8585

**Comment by steve1316** [comment]
I could not replicate that exact button when I just ran my Lindwurm, but I decided to just simply crop the image asset itself to only include the "FULL" text and not the full button itself to avoid situations like this. Let me know how it goes!

**Comment by PortablePanda** [comment]
To get that button in 2.0, you have to turn both Full Auto and Auto Guard on.

**Comment by steve1316** [comment]
Ah, thanks for letting me know. Just tested it and the new cropped version works.

**Comment by steve1316** [comment]
Closing issue as the issue has been fixed.
