### ISSUE TITLE
Campaign Exclusive Quest

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#50]
Hello! The button for the Campaign Exclusive Quest is named "campaign-exclusive_quest.png", but the bot is looking for "campaign_exclusive_quest.png", which causes it to fail and terminate.

**Comment by steve1316** [comment]
Cannot believe that I let that slip through. Fixed it just now!

**Comment by steve1316** [comment]
Closing issue as this has been fixed.
