### ISSUE TITLE
Guild Wars Meat Farming Deadzone

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#52]
It seems as though the bot's click to start farming meat is in an area that doesn't register the button being pressed. Clicking near the AP cost or the picture works properly, but clicking between them doesn't proceed.

Also, it seems as if with Bezier curve disabled, the bot doesn't click on randomized positions?

**Comment by steve1316** [comment]
I was able to replicate the issue with the deadzone so a fix will be out soon.

I just tested the randomized clicking position behavior for both disabled and enabled Bezier curve and they both randomized their positions. Can you describe the situation in where you saw that it did not?

**Comment by PortablePanda** [comment]
Such as when clicking the meat farming quest, selecting a summon, or going to the Guild Wars event page, the bot clicks the same area each time. How randomized is the area meant to be?

**Comment by steve1316** [comment]
The randomized clicking position is within 20% to 80% of both width and height of the provided template image. If the template image is small for example, that will explain why it seemed that it clicks on the same area because there is not much to work with inside the 20% to 80% available area.

**Comment by PortablePanda** [comment]
Good to know!

Also, an update. When attempting to farm either NM90 or NM95, I'm running into an error where the bot terminates as soon as it tries to click the difficulty. The relevant section is:

```0:00:21 [ERROR] Bot encountered exception in Farming Mode: 
Traceback (most recent call last):
  File "D:\Desktop\granblue-automation-pyautogui-main\bot\game.py", line 1217, in start_farming_mode
    self._map_selection.select_map(farming_mode, map_name, mission_name, difficulty)
  File "D:\Desktop\granblue-automation-pyautogui-main\bot\map_selection.py", line 1083, in select_map
    self._navigate_to_guild_wars(difficulty)
  File "D:\Desktop\granblue-automation-pyautogui-main\bot\map_selection.py", line 948, in _navigate_to_guild_wars
    self._game.mouse_tools.move_and_click_point(nightmare_locations[1][0], nightmare_locations[1][1], "guild_wars_nightmares")
IndexError: list index out of range
```

**Comment by steve1316** [comment]
Thanks for letting me know, just updated the image asset so that 95s and hopefully 100s and 150s work later on.
