### ISSUE TITLE
Event Drawbox Difficulty Deadzone

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#53]
Just like with Guild Wars, the current clicking zone between the AP and the difficulty is a deadzone.

Maybe making the clicking selection area something like this would work better? 
![image](https://user-images.githubusercontent.com/82384904/127743027-4577d488-b4f6-466e-be67-4abfe4e77f2a.png)

**Comment by steve1316** [comment]
Okay just pushed an update fixing this bug. Let me know how it goes!

**Comment by zorkings** [comment]
still occurring for me, also is unable to detect ex/impossible events buttons for me either

**Comment by steve1316** [comment]
Thanks for letting me know. Just pushed an update fixing that.

**Comment by zorkings** [comment]
Impossible is now correctly working for me.
