### ISSUE TITLE
Exit no longer exiting

### ISSUE THREAD

**Issue by zorkings** [steve1316/granblue-automation-pyautogui#55]
Whenever my script reads to exit it just runs an attack and refreshes, used to work (haven't used in pretty long time)

![image](https://user-images.githubusercontent.com/77841008/127793066-4fcc9a16-c637-487f-af60-428adc3c7640.png)

**Comment by steve1316** [comment]
I too have not used this command in a long while so this slipped past me. Just pushed an update fixing this.

**Comment by zorkings** [comment]
Still occurring for myself

**Comment by steve1316** [comment]
Just tested with Europa raid using this script:

```
Turn 1:
	summon(6)
	character1.useSkill(1)
	
	character3.useSkill(1)
	character2.useSkill(2)
end

Turn 5:
	exit
end
```

It successfully exited to the Home screen at the end. Can you post your message log and combat script here for me to take a look at?

**Comment by zorkings** [comment]
I see, I put the exit into Turn2: and it works, sorry I didn't know that was the syntax I didn't have it inside of the next turn. Working now.
