### ISSUE TITLE
Shenxian Hosting

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#57]
Requesting Shenxian hosting functionality for RoTB, please!

**Comment by PortablePanda** [comment]
Also, piggy-backing onto this, could we get RoTB EX+ and Shenxian added to the raid joining section?

**Comment by steve1316** [comment]
Added support for farming Shenxian and ROTB EX+ Raids. Let me know how it goes!

**Comment by steve1316** [comment]
Also added support for hosting Shenxian.

**Comment by PortablePanda** [comment]
Thank you, so far, everything's great! Also, I didn't consider this at the time, but could you also add support for joining Huanglong and Qilin HL raids? They don't die as quickly as I expected, so there's enough time to automate joining.

**Comment by PortablePanda** [comment]
Awesome! Can't wait to use it!

**Comment by steve1316** [comment]
Closing issue as ROTB has ended.
