### ISSUE TITLE
ROTB Ex+ Config Script

### ISSUE THREAD

**Issue by zorkings** [steve1316/granblue-automation-pyautogui#58]
If the auto ap consumption pop up occurs during ROTB ex+ being found it will default back to the original script ignoring the config settings

![image](https://user-images.githubusercontent.com/77841008/128651200-1322b340-38c8-4534-aabb-cae765c67102.png)

Will try to get log next time this occurs if needed

**Comment by steve1316** [comment]
Whoops, there was a typo in the code that led to the bot defaulting to your original script during ROTB+. Fixed it so let me know how it goes.

**Comment by zorkings** [comment]
Still occurred, selected the default combat script/party selection

**Comment by steve1316** [comment]
Hmm, I tried testing again. 

My original settings was Group 1, Party 1 and the full auto script for Zhuque. When it detected EX+, it successfully switched over to Group 1, Party 4 and my custom script for Agni.

Can you double check again to see if it works on your end?

**Comment by zorkings** [comment]
Recloned the repo and it seems to be working now.

**Comment by zorkings** [comment]
Nevermind, occurred again attached is log
[log (1).txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6958969/log.1.txt)

**Comment by steve1316** [comment]
![notepad++_hMAKBd1iLc](https://user-images.githubusercontent.com/18709555/128809076-daa467cc-0ad4-4063-ac2e-d90541e89437.png)

Can you take a screenshot like this from your config.ini and post it here? What Group/Party you wanted and the name of the combat script that you wanted to take to EX+?

**Comment by zorkings** [comment]
![image](https://user-images.githubusercontent.com/77841008/128809969-9cde8fd6-ae5d-4597-852c-00a8d41f6f75.png)

**Comment by steve1316** [comment]
Okay looking at it, you have set the full auto script and Group 2, Party 1 as your setup for EX+. In your log, it shows exactly that. What did you wanted to happen instead of having the full auto script and Group 2, Party 1 for EX+?

**Comment by zorkings** [comment]
That is what I expected to happen, but when the autofill AP occurs it reverts back to the initial EX (waterrb.txt) (non plus) configuration instead of selection the proper EX+ script (full_auto)

**Comment by steve1316** [comment]
![chrome_CjbQPF4N71](https://user-images.githubusercontent.com/18709555/128810958-08fb48e4-f8d8-4fcf-832d-2b3f6021c3e5.png)

Try enabling this under Miscellaneous to forever hide all popups about autofill AP/EP.

Also I finally see what you mean. I will check it out on my end.

**Comment by zorkings** [comment]
Did not realize that was even put in with the auto ep/ap usage, wow that saves myself a lot of headache with normal gameplay as well. Will try and let you know.

**Comment by zorkings** [comment]
Well with that notification change everything is now going smoothly.
