### ISSUE TITLE
Request Backup Error

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#59]
It seems like Request Backup currently scrolls down, then fails to click the button and causes battle mode to terminate.

**Comment by steve1316** [comment]
Alright, I fixed the issue. Apparently, the Request Backup button had its text moved slightly to the right for some reason so I made the new image asset more general to account for cases like this. Let me know how it goes!

**Comment by PortablePanda** [comment]
Seems to be fixed, thank you!
