### ISSUE TITLE
Dread Barrage

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#6]
Hello there Steve!

Keep up the good work!

I know this is pretty tall order but I couldn't make the event tab work with the new event "Dread Barrage".

Could you please check it?

qwe8585.

**Comment by steve1316** [comment]
The Event Farming Mode pertains to Events where there are farmable trade-in items like "Elegy Auld Lang Syne" and "A Tale of Kindled Bonds". The others, like Guild Wars, ROTB, and Dread Barrage, are currently not supported. Sorry for the misunderstanding.

I will work on  support for Dread Barrage tomorrow.

**Comment by steve1316** [comment]
Just pushed several updates such that the bot now supports Dread Barrage and fighting Unparalleled Foes. Let me know how it goes!

**Comment by qwe8585** [comment]
Thanks Steve it works!

But can we get support for pending battles like we have in raid battles?

**Comment by qwe8585** [comment]
Another observation steve there is this popup: 
![image](https://user-images.githubusercontent.com/17860803/107753221-142ff380-6d20-11eb-96b5-1dd860f7c546.png)
when the battle ends the bot gets stuck on it

**Comment by qwe8585** [comment]
Another another observation is that when the battle ends in dread barrage the script gets stuck on the 
![image](https://user-images.githubusercontent.com/17860803/107753592-8ef90e80-6d20-11eb-8f2c-6ebe18faace1.png) loot collected check but it actually clicks away all the popups.

**Comment by steve1316** [comment]
Thank you for letting me know about these new bugs. 

I was able to replicate the lack of support for pending battles during Dread Barrage and a fix will be out soon.

For the issue of "This battle has ended" during Combat Mode, did it occur while you were the only person inside that Dread Barrage mission or were there others with you?

Additionally, for the issue of the infinite loop when collecting loot, did you happen to save the text log from when it happened? Did you also happen to take a screenshot of the game screen? Having these available would greatly help me in pinpointing the issue.

**Comment by steve1316** [comment]
Just posted a fix for the lack of support for Pending Battles during a Dread Barrage Raid. I have not been able to replicate the other 2 issues as I need more information. 

I suspect that Commit 429b7b05d0069fe9486c3ff6fcf8c97fb6229a48 may have also fixed your infinite looping on trying to confirm the location at the "Loot Collected" screen. Let me know how it works out for you!

**Comment by steve1316** [comment]
Made a temporary fix in Commit 9efca4db7e2f34fe4e8def1c7e18ad1848ba375c to attempt to address the issue of "This battle has ended" during Combat Mode. I have not been able to replicate the same issue in my tests so I am unsure if this fix will work or not.

**Comment by qwe8585** [comment]
Thanks a bunch Steve for the heads ups.

I will try to save as many pictures and logs as I can. I will get on with testing the newest changes.

**Comment by qwe8585** [comment]
![image](https://user-images.githubusercontent.com/17860803/107845211-34bc8400-6dda-11eb-9fb8-30f5de3c9053.png)

[log 1.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/5975315/log.1.txt)

**Comment by qwe8585** [comment]
Oh my Steve I just got it. In dread barrage as long as you have one raid started you can't start another one. I don't know if this for all raids in GBF cause I'm kind of a noob. So maybe the pending battle system won't work out so well. Sorry about that one.

**Comment by qwe8585** [comment]
I can confirm it that the loot loop is gone Steve.

**Comment by steve1316** [comment]
Yes, that is correct. Once you host a quest/raid, you cannot host anything else until you complete it or retreat from it. But for joining raids, you can join up to a max of 3 raids without worry.

Looking at the log that you posted earlier, turns out you wiped during Combat Mode and the bot tried to retreat but failed. That is a bug that only could have come to light because you provided the logs for it so thank you! It seems to be the main source of trouble as to why you think it must have been a Pending Battle issue. Will be posting a fix soon.

**Comment by qwe8585** [comment]
Yeah thanks for clearing that up Steve.

**Comment by steve1316** [comment]
Posted a new update that overhauled the logic for checking if the party wiped or not.

**Comment by qwe8585** [comment]
Sorry Steve I'm going off topic here. 

How many shiny slime searches can you do in 1 hour?

**Comment by steve1316** [comment]
On Very Hard, I can do 25 on my virtual machine while in Full Auto. Additionally, I do not have Sarasa or Swordmaster.

I will be closing this issue as Dread Barrage is now over.
