### ISSUE TITLE
Arcarum Mode

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-pyautogui#63]
First off, thank you so much for adding this! Maybe those 70 tickets I have will actually end up getting used now, and fingers crossed for Replicard support in the future.

Just popping in to say that it seems as if CAPTCHAs which appear after clicking a node to start a fight and before selecting your party aren't checked for, and requesting a method to either stop the bot or allow for a script/party to be chosen for Stage 3/6/9 bosses.

**Comment by steve1316** [comment]
Thank you for your feedback!

To clarify, the CAPTCHA appears after clicking on a node before moving to it? Or does it appear after moving to the node? And all of this happens before the Party Selection screen shows up right?

I will add some new fields into config.ini to allow setting script/party for 3/6/9 bosses.

For Replicard support, I have not played Sandbox much so it may take a while for me to implement support for it.

**Comment by PortablePanda** [comment]
I'll record my screen next time to double-check, but I'm 90% sure it's after you move to the node and click the fight, the CAPTCHA shows up, and then after solving it, the party selection screen loads. I remember the background being black when the CAPTCHA displayed.

As for the boss settings, will you be able to set them based on the specific boss, or the element? Being able to tell the bot to stop for 9 bosses or automatically use Globes to change to the desired boss would be neat too, but I can understand if that's a bit much.

And for Replicard, that's fine! I don't play it much myself as I have a fair bit more progress to do, but here's hoping for the far future.

**Comment by PortablePanda** [comment]
Okay, found the problem! When the enemies have a pre-emptive attack, the attack button won't appear until they complete it. And they won't perform their attack until the stage effect prompt is dismissed.

**Comment by steve1316** [comment]
Just updated the bot to fix the issue where the bot can get stuck if there is a stage effect popup on screen during Combat Mode.

Added an option in the config.ini to stop upon detection of any Arcarum boss (3-3, 6-3 and 9-3). This will ensure that you can use a Globe yourself to change the boss to whichever one you need. Will require regenerating the config.ini by deleting it and running the application again.

**Comment by PortablePanda** [comment]
Another issue! It seems like the Arcarum bot doesn't properly handle Skyscope rewards after each run.

**Comment by steve1316** [comment]
Forgot to mention that the handling of Skyscope rewards after each completed expedition was included in the recent merged pull request.

**Comment by PortablePanda** [comment]
Another error! It seems as though Arcarum isn't handling Do or Die pop-ups properly, and infinitely loops trying to click a map node.

**Comment by steve1316** [comment]
Closing this issue as Arcarum Mode has been fleshed out in general. A specific issue with Arcarum Mode can be opened in the future.
