### ISSUE TITLE
Unexpected reloading in Angel Halo VH

### ISSUE THREAD

**Issue by NeapolitanIcecream** [steve1316/granblue-automation-pyautogui#69]
Observing unexpected reloading in Angel Halo VH.

The following is how I think it happened:

[Here](https://github.com/steve1316/granblue-automation-pyautogui/blob/d6ce2521007be2d339fd6566ef6b600beda73d67/bot/game.py#L1212) `difficulty` is set to `"Very Hard"`, so [here](https://github.com/steve1316/granblue-automation-pyautogui/blob/b74db100c680ba74a8ff66da0d3e1e7c821c44d8/bot/combat_mode.py#L470) Angel Halo is mistaken for Guild Wars.

**Comment by steve1316** [comment]
Thank you for letting me know about this. Updated the logic to not reload during Angel Halo. Let me know how it goes!

**Comment by NeapolitanIcecream** [comment]
Look good to me. Thank you!
