### ISSUE TITLE
Event quest

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#7]
Hello there Steve!

It's me again.

The new story event is here and I wanted to farm some materials. Problem is the script can't find the special quest tab.

I'm linking the log and the picture below.

qwe8585.

![image](https://user-images.githubusercontent.com/17860803/108362901-9c1c6e80-71f4-11eb-9980-a6b5860d7066.png)

[event.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6003035/event.txt)

**Comment by steve1316** [comment]
Thanks for bringing it to my attention. Currently, the Event Mode only works for Events whose UI layout was like "A Tale of Kindled Bonds" that had Token Drawboxes. Was waiting for this event so that I can work on supporting this UI layout without Token Drawboxes.

I will get an update out supporting this type of Event as soon as I am done with the Event story and finalize a few of my on-going work these past few days.

**Comment by qwe8585** [comment]
Sure Steve thank you!

**Comment by steve1316** [comment]
Just added support in the latest update. I have separated both types of Events into two modes: 
"Event" and "Event (Token Drawboxes)" in the GUI. 

From now on, events such as this current one right now where it does not have Token Drawboxes on the event page can be farmed via "Event" and the ones with Token Drawboxes can be farmed via "Event (Token Drawboxes)".

Let me know how it goes for you!

**Comment by qwe8585** [comment]
It definitely works now Steve!

Here are my observations:

![Spaghet Syndro](https://user-images.githubusercontent.com/17860803/108475402-ef43ff00-7290-11eb-94fa-8e752ce42060.png)

[birthedfromrecords.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6008474/birthedfromrecords.txt)

**Comment by qwe8585** [comment]
When the nightmare run is open the script tries to open that one instead of the normal quests

**Comment by steve1316** [comment]
Thanks for letting me know! A fix is in the works.

**Comment by steve1316** [comment]
Just uploaded a fix in regards to Event Nightmares. Let me know how it goes!

**Comment by qwe8585** [comment]
Thanks again Steve!

**Comment by steve1316** [comment]
Closing issue as the Event is now over.
