### ISSUE TITLE
Skill targeting allies

### ISSUE THREAD

**Issue by masayuki232** [steve1316/granblue-automation-pyautogui#71]
how to use skill with allies targeting in the script ?
For example grand noa's 3rd skill or etc

**Comment by steve1316** [comment]
Currently the bot has `targetEnemy(#)` but it does not have a command to target allies. I will add that to the TODO list.

**Comment by steve1316** [comment]
Just updated the wiki with the missing documentation on `.target(#)`:

![firefox_0unEwKBxRE](https://user-images.githubusercontent.com/18709555/132563139-e4b91ce8-8014-4c5d-863e-e11b1c5810bc.png)

Let me know how it goes!
