### ISSUE TITLE
Avatar twitter failed to find

### ISSUE THREAD

**Issue by zorkings** [steve1316/granblue-automation-pyautogui#72]
Unable to find Avatar (Impossible) rooms, have no problem with any other raids I've tried

**Comment by steve1316** [comment]
Yeah, this is a known persisting issue that I have no solution for. The raid itself is censored on Twitter if you try to search it normally using `Lvl 120 Avatar/Lv120 アバター`. Not sure how sites like gbf.life bypass the censorship.

**Comment by zorkings** [comment]
Got it
