### ISSUE TITLE
Twitter search API is unable to search Lvl 120 Avatar (flagged as sensitive tweet)

### ISSUE THREAD

**Issue by lamp333** [steve1316/granblue-automation-pyautogui#73]
Twitter is flagging **Lvl 120 Avatar** tweets as sensitive, which causes zero results to appear when the tweepy api is searching for available tweets. 

Instead of using the search api from tweepy's wrapper, using a tweet streaming api can probably let you specify/set the filter level.

**Comment by lamp333** [comment]
Closing this as redundant

**Comment by PortablePanda** [comment]
I would at least keep this until Steve sees it, since it sounds like it has a good suggestion. Best case, it's a viable fix, worst case, it's not feasible.

**Comment by lamp333** [comment]
I added my comments on the other issue instead.
