### ISSUE TITLE
UI QOL recommendations 

### ISSUE THREAD

**Issue by lamp333** [steve1316/granblue-automation-pyautogui#78]
Just a few QOL suggestions I thought might be really useful:

1. Instead of having to scroll down through the UI to look for items raid names, items, etc, we should be able to search these by name.

2. Having a persistent state of the settings configuration, which you could store the representation in a file i.e **settings.ini** similar to config.ini.
- On application launch if the file doesn't exist you can just create an empty/default **settings.ini** file, which we are already doing for config.ini. 
- In the scenario we already have settings.ini we could preload the settings from file instead
- You could then implement a termination handler to save the current settings into **settings.ini**

**Comment by steve1316** [comment]
Will definitely put these on the TODO list. 👍

**Comment by steve1316** [comment]
These suggestions have now been implemented and merged into the main branch.
