### ISSUE TITLE
Support for Campaign-Exclusive Quest

### ISSUE THREAD

**Issue by qwe8585** [steve1316/granblue-automation-pyautogui#8]
Hello there Steve! If you have the time I have another request. There is this new very efficient quest in gbf.

![image](https://user-images.githubusercontent.com/17860803/108768304-ca34e200-7557-11eb-906c-b331a7312257.png)

**Comment by steve1316** [comment]
Just posted an update. Program now supports farming this time-limited mission under the "Special" Farming Mode section on the GUI. You can start it by selecting the "EXP" item and scrolling down and selecting the "Campaign-Exclusive Quest" under Missions.

Let me know how it goes!

**Comment by steve1316** [comment]
Closing issue as the Campaign-Exclusive Quest event has now ended.
