### ISSUE TITLE
Commands after Turn 1 are ignored and will continually auto attack until end.

### ISSUE THREAD

**Issue by catly1** [steve1316/granblue-automation-pyautogui#80]
https://github.com/steve1316/granblue-automation-pyautogui/blob/b8422233449f2b7eb8a3b0498b1a53cf71a6bbb7/bot/combat_mode.py#L686-L687

This breaks the while loop after turn 1 and ignores everything past it in the script.
Replacing break with continue fixes it though.

**Comment by steve1316** [comment]
Oversight on my part! Thank you for letting me know!

**Comment by catly1** [comment]
It's working great now. Thanks!
