### ISSUE TITLE
Dimensional Halo problem

### ISSUE THREAD

**Issue by KoiKomei** [steve1316/granblue-automation-pyautogui#84]
Attached log file
[angelhalo.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/7192290/angelhalo.txt)

It seems that the bot fails to go back to angel halo after finishing Dimensional Halo because it tries to search for a summon on the quest result page.

Before it used to go back home and then go back to special quests and restart angel halo.

**Comment by steve1316** [comment]
Just fixed that. Let me know how it goes!

**Comment by KoiKomei** [comment]
It seems to be working correctly, we can close this one
