### ISSUE TITLE
Farming repeatable quests

### ISSUE THREAD

**Issue by KoiKomei** [steve1316/granblue-automation-pyautogui#9]
I've been testing out the program and, while the raids with full auto work correctly, Angel Halo is a bit weird to farm given that you usually farm it by using Semi-auto instead of Full Auto. 
The combat script doesn't allow to put Semi-auto, neither it allows to put full auto after attacking, for example:

```
Turn 1:

end

Turn 2: 

end

Turn 3:

end
```

This simulates semi-auto but after it reaches the 3rd "end" it just stops working since there's no "exit" and "exit" will return to home, skipping the nightmare proc and just making the whole process way longer (it also repeats infinitely since it can't check the quest items).
This could be circumvented by either allowing to enable fullAuto after "end" so that 
```
Turn 3:

end
enableFullAuto
```
is possible and it will check the result screen since Full Auto clicks the "next" button automatically or by implementing "enableSemi" where it will skip directly to attack, enable semi-auto and then make it act like the "enableFullAuto" routine.

Thanks

**Comment by KoiKomei** [comment]
The "exit" command was explained very well in the tutorial given by you and I understood it without any problems, mine was just a comment of the kind "I could use Exit for angel halo, but it just isn't what it is meant for".

Thank you for your work.

**Comment by steve1316** [comment]
Just posted an update adding a new command called `enableSemiAuto` and updated the wiki page with documentation of it as well. Let me know how the new command goes for you!

**Comment by KoiKomei** [comment]
It is working perfectly, can't really ask for better.
Meanwhile i'm working on my fork (also just pulled this update), where I "enabled" multiple summons choices. 
It is still a bit buggy but the "big" part should be done, so if you open a develop branch or an "outsider" branch, I can do a pull request on it and you can check it out.

**Comment by steve1316** [comment]
Thank you for the feedback! I have opened up a new branch called `multiple-summon-choices` for you.

**Comment by KoiKomei** [comment]
Perfect, this issue can be closed.
