### ISSUE TITLE
Twitter API test not successful

### ISSUE THREAD

**Issue by Chu2P** [steve1316/granblue-automation-pyautogui#95]
Having followed the slightly outdated instructions at https://github.com/steve1316/granblue-automation-pyautogui/wiki/Instructions-for-Farming-Raids I have filled out the twitter settings, however when I run test twitter API it claims test not successful

**Comment by steve1316** [comment]
Hmm, I reviewed the instructions in the wiki page and made some minor updates to it but overall, the instructions have not changed. I also tried the Test Twitter API and it works fine. Can you check your settings.json file in the /backend/ folder and see if the ```twitter``` section is filled out the same as the fields in the Extra Settings page? The file is updated in real-time as you make changes to their respective fields in the Extra Settings page.

**Comment by fullblue** [comment]
elevated access is needed, go to https://developer.twitter.com/en/portal/dashboard and request it.

**Comment by steve1316** [comment]
Yeah, you can apply for elevated access to v1.1 endpoints. I will see if I can set aside some time to add support for v2 endpoints in the meantime.

**Comment by Chu2P** [comment]
I have acquired elevated access, and it all seems to be working correctly now, thanks
