### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by colpocleisis** [steve1316/granblue-automation-pyautogui#97]
Howdy, awesome bot!

Was wondering if you could add the option in the settings to skip checking for the party each time since the browser saves your last selected party and many uses the same setup each time for farming.

Another feature I would request would be the option to automate hosting raids.

Thank you very much

**Comment by steve1316** [comment]
The bot already has the feature to skip party selection after it selects it for the first time for every subsequent run after the bot starts. 

For the feature of being able to host raids, that will be put onto the TODO list but I don't see myself tackling that for some time.

**Comment by colpocleisis** [comment]
Some other issues I found would be the bot doesnt seems to be able to handle trophy/skyscope mission popups, and do or die events in arcarum in conjunction with a treasure chest as it just stalls

```
1:15:08 [CAPTCHA] CAPTCHA not detected.
1:15:08 [WARNING] Failed to confirm the bot's location at ARCARUM_PARTY_SELECTION.
1:15:09 [WARNING] Failed to find the OK button.
1:15:09 [ARCARUM] Action to take will be: Claimed Spirethorn
```

**Comment by steve1316** [comment]
Fixed the stuck loop on the Treasure + Do or Die combo in Arcarum, but I saw no issue with clearing away trophy/skyscope mission popups.
