### ISSUE TITLE
Twitter can't find raid code?

### ISSUE THREAD

**Issue by fullblue** [steve1316/granblue-automation-pyautogui#99]
![image](https://user-images.githubusercontent.com/65227601/148076412-a30ee91f-83f9-4703-9a8a-f0fc2af5111d.png)
I keep getting this with most raid, it's strange since raid finder is working fine. Probably my own connection issue or twitter account, idk

**Comment by fullblue** [comment]
Updated to newest version and the bug so far has not come back

**Comment by steve1316** [comment]
This is a problem with Twitter as it sometimes does not return anything in the search. One person has said that regenerating keys helped fixed this while another said they waited several hours before trying again.
